# fly.toml app configuration file generated for demo-expenses-1 on 2024-01-14T15:36:01-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "demo-expenses-1"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  KINDE_DOMAIN="https://codegpt.kinde.com"
  KINDE_REDIRECT_URI="https://demo-expenses-1.fly.dev/callback"
  KINDE_LOGOUT_REDIRECT_URI="https://demo-expenses-1.fly.dev"